# Generated by Django 5.1.7 on 2025-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date_visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='date_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
