# Generated by Django 5.1.7 on 2025-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_visit_date_visit_visit_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
