# Generated by Django 5.1.7 on 2025-03-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_slug'),
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='date_visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
